//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaburMarketObservatoryMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Advertisement
    {
        public int advert_id { get; set; }
        public string aspNetUsersId { get; set; }
        [Display(Name = "⁄‰Ê«‰ «·„Õ«÷—…")]
        public string advert_title { get; set; }
        [Display(Name = "«”„ «·„Õ«÷—")]
        public string advert_lecturer { get; set; }
        [Display(Name = " «—ÌŒ «·„Õ«÷—…")]
        public System.DateTime advert_date_lecture { get; set; }
        [Display(Name = "„ﬂ«‰ «·„Õ«÷—…")]
        public string advert_lecture_place { get; set; }
        [Display(Name = "„›⁄· «„ ·«")]
        public Nullable<bool> advert_isActive { get; set; }
        [Display(Name = " «—ÌŒ «·‰‘—")]
        public Nullable<System.DateTime> advert_publish_date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
