//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaburMarketObservatoryMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.Advertisements = new HashSet<Advertisement>();
            this.ApplicantToJobOffers = new HashSet<ApplicantToJobOffer>();
            this.ApplicantToTrainings = new HashSet<ApplicantToTraining>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUserRoles = new HashSet<AspNetUserRole>();
            this.CompanyQuestionnaires = new HashSet<CompanyQuestionnaire>();
            this.Feedbacks = new HashSet<Feedback>();
            this.JobOffers = new HashSet<JobOffer>();
            this.SeekerQuestionnaires = new HashSet<SeekerQuestionnaire>();
            this.Reports = new HashSet<Report>();
            this.CompanySstatistics = new HashSet<CompanySstatistic>();
            this.SeekerStatistics = new HashSet<SeekerStatistic>();
            this.Trainings = new HashSet<Training>();
        }
    
        public string Id { get; set; }
        [Display(Name = "«·»—Ìœ «·«·ﬂ —Ê‰Ì")]
        public string Email { get; set; }
        [Display(Name = " √ﬂÌœ «·»—Ìœ «·«·ﬂ —Ê‰Ì")]
        public bool EmailConfirmed { get; set; }
        [Display(Name = "ﬂ·„… «·„—Ê—")]
        public string PasswordHash { get; set; }
        [Display(Name = "„„Ì“ «·Õ„«Ì…")]
        public string SecurityStamp { get; set; }
        [Display(Name = "—ﬁ„ «·Â« ›")]
        public string PhoneNumber { get; set; }
        [Display(Name = " √ﬂÌœ —ﬁ„ «·Â« ›")]
        public bool PhoneNumberConfirmed { get; set; }
        //[Display(Name = "«·⁄«„·Ì‰ „›⁄·Ì‰")]
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        [Display(Name = "«·ﬁ›· „›⁄·")]
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        [Display(Name = "«”„ «·„” Œœ„")]
        public string UserName { get; set; }
        [Display(Name = "«·⁄‰Ê«‰")]
        public string address { get; set; }
        [Display(Name = "«·⁄„—")]
        public Nullable<int> age { get; set; }
        [Display(Name = "«·Ã‰”")]
        public string gender { get; set; }
        [Display(Name = "’Ê—… ‘Œ’Ì…")]
        public byte[] personal_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertisement> Advertisements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantToJobOffer> ApplicantToJobOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantToTraining> ApplicantToTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyQuestionnaire> CompanyQuestionnaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeekerQuestionnaire> SeekerQuestionnaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanySstatistic> CompanySstatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeekerStatistic> SeekerStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Training> Trainings { get; set; }
    }
}
