//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaburMarketObservatoryMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AspNetUserClaim
    {
        public int Id { get; set; }
        [Display(Name = "—ﬁ„ «·„” Œœ„")]
        public string UserId { get; set; }
        [Display(Name = "«·‰„ÿ")]
        public string ClaimType { get; set; }
        [Display(Name = "«·ﬁÌ„…")]
        public string ClaimValue { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
