//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaburMarketObservatoryMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Company
    {
        public string aspNetUsersId { get; set; }
        [Display(Name = "«”„ «·‘—ﬂ…")]
        public string comp_name { get; set; }
        [Display(Name = " Œ’’ «·⁄„·")]
        public string comp_special { get; set; }
        [Display(Name = "—«»ÿ „Êﬁ⁄ «·«·ﬂ —Ê‰Ì")]
        public string comp_page_link { get; set; }
        [Display(Name = "—ﬁ„ «· —ŒÌ’")]
        public int licensed_comp_licenseNumber { get; set; }
        [Display(Name = "’Ê—…")]
        public byte[] comp_image1 { get; set; }
        [Display(Name = "’Ê—…")]
        public byte[] comp_image2 { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SystemLicensedCompany SystemLicensedCompany { get; set; }
    }
}
