//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaburMarketObservatoryMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class JobSeeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobSeeker()
        {
            this.Skills = new HashSet<Skill>();
        }
    
        public string aspNetUsersId { get; set; }
        [Display(Name = "«·‘Â«œ… «·⁄·„Ì…")]
        public string seeker_certificate { get; set; }
        [Display(Name = "«· Œ’’ «·⁄·„Ì")]
        public string seeker_specialization { get; set; }
        [Display(Name = "⁄œœ ”‰Ê«  «·Œ»—…")]
        public Nullable<int> seeker_experience_years { get; set; }
        [Display(Name = "„ÊŸ› «„ ·«ø")]
        public bool seeker_isEmployeed { get; set; }
        [Display(Name = "’Ê—…")]
        public byte[] seeker_image1 { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
