//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaburMarketObservatoryMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Report
    {
        public int report_id { get; set; }
        public string aspNetUsersId { get; set; }
        [Display(Name = " «—ÌŒ «·‰‘—")]
        public System.DateTime report_date { get; set; }
        [Display(Name = "«·⁄‰Ê«‰")]
        public string report_title { get; set; }
        [Display(Name = "«· ﬁ—Ì—")]
        [DataType(DataType.Upload)]
        public byte[] report_file { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
