//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaburMarketObservatoryMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SeekerQuestionnaire
    {
        public int seeker_quis_id { get; set; }
        public string aspNetUsersId { get; set; }
        [Display(Name = "ÚÏã ÊæİÑ ÇáİÑÕÉ ÇáãäÇÓÈÉ")]
        public int no_suitable_opportunity { get; set; }
        [Display(Name = "ÓŞİ ÑÇÊÈ ãäÎİÖ")]
        public int low_pay { get; set; }
        [Display(Name = "ÇáÑæÊíä æŞÊá ÇáÇÈÏÇÚ")]
        public int routine { get; set; }
        [Display(Name = "Øæá İÊÑÉ ÇáÈÍË Úä Úãá")]
        public int long_job_seeking { get; set; }
        [Display(Name = "ÇáÎÈÑÇÊ ÛíÑ ßÇİíÉ")]
        public int not_enough_experience { get; set; }
        [Display(Name = "ÕÚæÈÉ ÔÑæØ ÇáÚŞÏ")]
        public int contract { get; set; }
        [Display(Name = "ŞÊá ÇáÇÈÏÇÚ")]
        public int kill_creativity { get; set; }
        [Display(Name = "ÊÍÏíË ÇáãÊæì ÇáÚáãí")]
        public int update_content { get; set; }
        [Display(Name = "ÇáÊÃåíá æÇáÊÏÑíÈ")]
        public int traning { get; set; }
        [Display(Name = "ãæÇßÈÉ ÇáÊØæÑ")]
        public int keep_updated { get; set; }
        [Display(Name = "ÒíÇÑÇÊ ÏæÑíÉ áÓæŞ ÇáÚãá")]
        public int field_trips { get; set; }
        [Display(Name = "ÊÇÑíÎ ÇáäÔÑ")]
        public Nullable<System.DateTime> seekerQuestionnair_publishDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
