//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaburMarketObservatoryMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeekerStatistic
    {
        public int statistic_seeker_id { get; set; }
        public string aspNetUsersId { get; set; }
        public Nullable<System.DateTime> statistic_seeker_date { get; set; }
        public double statistic_no_suitable_opportunity3 { get; set; }
        public double statistic_no_suitable_opportunity2 { get; set; }
        public double statistic_no_suitable_opportunity1 { get; set; }
        public double statistic_low_pay3 { get; set; }
        public double statistic_low_pay2 { get; set; }
        public double statistic_low_pay1 { get; set; }
        public double statistic_routine3 { get; set; }
        public double statistic_routine2 { get; set; }
        public double statistic_routine1 { get; set; }
        public double statistic_long_job_seeking3 { get; set; }
        public double statistic_long_job_seeking2 { get; set; }
        public double statistic_long_job_seeking1 { get; set; }
        public double statistic_not_enough_experience3 { get; set; }
        public double statistic_not_enough_experience2 { get; set; }
        public double statistic_not_enough_experience1 { get; set; }
        public double statistic_contract3 { get; set; }
        public double statistic_contract2 { get; set; }
        public double statistic_contract1 { get; set; }
        public double statistic_kill_creativity3 { get; set; }
        public double statistic_kill_creativity2 { get; set; }
        public double statistic_kill_creativity1 { get; set; }
        public double statistic_seeker_update_content3 { get; set; }
        public double statistic_seeker_update_content2 { get; set; }
        public double statistic_seeker_update_content1 { get; set; }
        public double statistic_traning3 { get; set; }
        public double statistic_traning2 { get; set; }
        public double statistic_traning1 { get; set; }
        public double statistic_keep_updated3 { get; set; }
        public double statistic_keep_updated2 { get; set; }
        public double statistic_keep_updated1 { get; set; }
        public double statistic_field_trips3 { get; set; }
        public double statistic_field_trips2 { get; set; }
        public double statistic_field_trips1 { get; set; }
        public Nullable<bool> statistic_seeker_isActive { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
