//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaburMarketObservatoryMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Skill
    {
        public int skill_id { get; set; }
        public Nullable<int> offer_id { get; set; }
        public string seeker_id { get; set; }
        [Display(Name = "«·„Â«—…")]
        public string skill_name { get; set; }
    
        public virtual JobOffer JobOffer { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
