//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaburMarketObservatoryMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Training
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Training()
        {
            this.ApplicantToTrainings = new HashSet<ApplicantToTraining>();
        }
    
        public int training_id { get; set; }
        public string aspNetUsersId { get; set; }
        [Display(Name = "„Ê÷Ê⁄ «·œÊ—…")]
        public string training_subject { get; set; }
        [Display(Name = "«”„ «·„œ—»")]
        public string training_instructor { get; set; }
        [Display(Name = "„ﬂ«‰ «·œÊ—…")]
        public string training_place { get; set; }
        [Display(Name = " «—ÌŒ «·»œ«Ì…")]
        public Nullable<System.DateTime> trainingStartDate { get; set; }
        [Display(Name = " «—ÌŒ «·‰Â«Ì…")]
        public Nullable<System.DateTime> trainingEndDate { get; set; }
        [Display(Name = " ﬂ·›… «·œÊ—…")]
        public Nullable<double> training_cost { get; set; }
        [Display(Name = " «—ÌŒ «·‰‘—")]
        public Nullable<System.DateTime> training_publishDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantToTraining> ApplicantToTrainings { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
